sudo: required
services:
  - docker

before_install:
  - docker build -t mersock/docker-react-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true mersock/docker-react-cicd npm run test
  #- docker run mersock/docker-react-cicd npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-southeast-1"
#   app: "docker-react-cicd"
#   env: "DockerReactCicd-env"
#   bucket_name: "elasticbeanstalk-ap-southeast-1-799067542302"
#   bucket_path: "docker-react-cicd"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"